Wanted packages

diff --git a/home/.chezmoiscripts/run_before_30-install-prerequisites.sh.tmpl b/home/.chezmoiscripts/run_before_30-install-prerequisites.sh.tmpl
--- a/home/.chezmoiscripts/run_before_30-install-prerequisites.sh.tmpl
+++ b/home/.chezmoiscripts/run_before_30-install-prerequisites.sh.tmpl
@@ -6,31 +6,35 @@
 true || source ../.chezmoitemplates/scripts-library
 
 readonly wanted_packages=(
-  git  # used to find the latest revisions of github repositories
-  curl # used to find the latest version of github repositories
-  jq   # used on modify_ scripts like docker daemon.json
-  # {{ if not .is_devcontainer }}
-  gpg # used to decrypt the gpg keys of the apt repositories
-  # {{ end }}
+    git  # used to find the latest revisions of github repositories
+    curl # used to find the latest version of github repositories
+    jq   # used on modify_ scripts like docker daemon.json
+    vim
+    zsh
+    htop
+    wget
+    # {{ if not .is_devcontainer }}
+    gpg # used to decrypt the gpg keys of the apt repositories
+    # {{ end }}
 )
 missing_packages=()
 
 for package in "${wanted_packages[@]}"; do
-  if ! command -v "${package}" >/dev/null; then
-    missing_packages+=("${package}")
-  fi
+    if ! command -v "${package}" >/dev/null; then
+        missing_packages+=("${package}")
+    fi
 done
 
 if [[ ${#missing_packages[@]} -gt 0 ]]; then
-  log_task "Installing missing packages with APT: ${missing_packages[*]}"
+    log_task "Installing missing packages with APT: ${missing_packages[*]}"
 
-  # This script also gets called when running rootmoi
-  # {{ if eq .chezmoi.username "root" }}
-  apt_command=(apt)
-  # {{ else }}
-  apt_command=(sudo apt)
-  # {{ end }}
+    # This script also gets called when running rootmoi
+    # {{ if eq .chezmoi.username "root" }}
+    apt_command=(apt)
+    # {{ else }}
+    apt_command=(sudo apt)
+    # {{ end }}
 
-  c "${apt_command[@]}" update
-  c "${apt_command[@]}" install --yes --no-install-recommends "${missing_packages[@]}"
+    c "${apt_command[@]}" update
+    c "${apt_command[@]}" install --yes --no-install-recommends "${missing_packages[@]}"
 fi
